openapi: 3.0.3
info:
  title: Simple Pet API
  description: A simple API to test code generation
  version: 1.0.0

servers:
  - url: http://localhost:8080/api

paths:
  /pets:
    get:
      summary: List all pets
      operationId: listPets
      tags:
        - pet
      responses:
        '200':
          description: A list of pets.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'

components:
  schemas:
    Pet:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
      required:
        - id
        - name